name: Enhanced Video Dubbing Automation
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - ffmpeg
  - git
  - pip
  - pip:
    - transformers>=4.30.0
    - accelerate>=0.20.0
    - openai-whisper>=20231117
    - librosa>=0.10.0
    - noisereduce>=3.0.0
    - speechbrain>=0.5.0
    - moviepy>=1.0.3
    - soundfile>=0.12.0
    - psutil>=5.9.0
    - dtw-python>=1.3.0
    - gitpython>=3.1.0
    - jupyter>=1.0.0
    - tqdm>=4.65.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
